### PR TITLE
Corrections

### PR DESCRIPTION
**Pull request by ydre**
Corrections of somes writing/rewriting problems. Cleaned code and algo. Added more comments.

### CODE REVIEW

**Comment by benchoufi** [comment]
yes, for me it is Ok. I just have one remark : the correct markdown write for that   

## Contributors
 -
 -* https://github.com/ydre
 -* https://github.com/morphus121
 -* Mathieu Regnier

is 

## Contributors
 -
 -* [ydre](https://github.com/ydre)
 -* [morphus121](https://github.com/morphus121)
 -* [Mathieu Regnier](https://github.com/Regnier-Mathieu)

**Comment by benchoufi** [comment]
@ydre could you commit the small changes so that we can merge :)

**Comment by ydre** [comment]
done

2016-08-25 14:40 GMT+02:00 @nowami <notifications@github.com>:

**Comment by benchoufi** [comment]
fine ;)

**Pull request merged**
