### PR TITLE
resolving conflict..

### PR DESCRIPTION
**Pull request by ydre**

### CODE REVIEW

**Comment by benchoufi** [comment]
@ydre could you please refactor these two heavy loops ?

for(i = 0; i < nbPix; i++){
        grille[i] = new Array();
            for(var j=0 ; j < len; j++){
    	       grille[i][j]= data[i+(j*nbPix)]; 
            };
    };

/*  lets write on it              */
    for(var i=0; i < nbPix; i++){
        fs.appendFile('./public/img.txt', '\n');
        for(var j=0; j < len; j++){
        	if(!isNaN(grille[i][j])){
             fs.appendFile('./public/img.txt',  grille[i][j]+ " ", function(err){
        	       if(err){console.log(err)};

**Comment by benchoufi** [comment]
hi again @ydre I have two questions 

- I don't see any fix of these redundant loops. Were you able to deal with that issue ? 

- Besides, I notice in your last commits that the README file shows a line `rm everything else except  /journal`. Do you mean this is an absolute path ?

**Comment by ydre** [comment]
- Fixed loops.
- Fixed README ( /data/db/ is the absolute path, created by default by
Mongodb ), however this is still a test version, have to find how to use
mongodb more easily.
- Fixed req.body settings in routes_settings.js

C webclient is now outdated, i have to test the whole server with the new
C script version.


2016-07-16 14:10 GMT+02:00 @nowami <notifications@github.com>:

**Comment by benchoufi** [comment]
@ydre cool, merged ;)

**Pull request merged**
